[script] sync make-pretty scripts from openthread
- Also reformat files.

diff --git a/script/clang-format-check b/script/clang-format-check
--- a/script/clang-format-check
+++ b/script/clang-format-check
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-#  Copyright (c) 2019, The OpenThread Authors.
+#  Copyright (c) 2018, The OpenThread Authors.
 #  All rights reserved.
 #
 #  Redistribution and use in source and binary forms, with or without
@@ -27,36 +27,24 @@
 #  POSSIBILITY OF SUCH DAMAGE.
 #
 
-readonly CUR_DIR="$(dirname "$(realpath -s $0)")"
-readonly CLANG_FORMAT_BIN=clang-format-6.0
-FILES="$(find ${CUR_DIR}/../include -name "*.hpp")"
-FILES="${FILES} $(find ${CUR_DIR}/../tests \( -name "*.cpp" -o -name "*.hpp" \))"
-readonly FILES="${FILES} $(find ${CUR_DIR}/../src \( -name "*.cpp" -o -name "*.hpp" \))"
+#
+# clang-format does not return a non-zero exit code.  This wrapper
+# exits with a non-zero exit code if clang-format outputs any
+# replacements.
+#
 
-check_clang_format_version() {
-    if [ ! -x "$(command -v ${CLANG_FORMAT_BIN})" ]; then
-        echo "${CLANG_FORMAT_BIN} not found"
-        exit 1
-    fi
+set -euo pipefail
+
+die() {
+    echo " *** ERROR:  $*"
+    exit 1
 }
 
-check_pretty() {
-    for file in ${FILES}; do
-        echo "${file}"
-        ${CLANG_FORMAT_BIN} -style=file ${file} | diff ${file} -
-    done
-}
+# from `man diff`:
+# Exit status is 0 if inputs are the same, 1 if different, 2 if trouble.
 
-make_pretty() {
-    set -e
-    for file in ${FILES}; do
-        echo "${file}"
-        ${CLANG_FORMAT_BIN} -i -style=file ${file}
-    done
-}
-
-set -e
-if [ ${BASH_SOURCE[0]} = ${0} ]; then
-    check_clang_format_version
-    check_pretty
-fi
+for file in "$@"; do
+    echo "Checking ${file}"
+    "$(dirname "$0")"/clang-format -style=file "${file}" | diff -u "${file}" - || die "${file} is not pretty."
+    [ -z "$(tail -c1 "${file}")" ] || die "${file} misses EOF newline."
+done
